# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a9c95d2c4ecc526d14ae944c9730bf259f7855cec281473efdc873112834171815251a15d2d62d13738a69c170cd9feef5e2e11e9230c45723766de2ef768050

test:
  secret_key_base: e77f28df9b24d1cd1fc606415f81e98e4749bca7e6844064bb8c0505698182157743791329a56fd0cf6aa025eac4ea4f225e238efe1a3863241794867350f2ab

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
